# Generated by Django 4.2.4 on 2023-09-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mow_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funfact",
            name="reaction",
        ),
        migrations.RemoveField(
            model_name="funfactcomment",
            name="reaction",
        ),
        migrations.AddField(
            model_name="funfact",
            name="downvote",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="funfact",
            name="upvote",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="funfactcomment",
            name="downvote",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="funfactcomment",
            name="upvote",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="funfact",
            name="updated_at",
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name="funfactcomment",
            name="updated_at",
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
    ]
