# Generated by Django 4.2.4 on 2023-10-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mow_api", "0004_funfactcomment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="funfactcomment",
            name="main_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_parent",
                to="mow_api.funfactcomment",
            ),
        ),
    ]
