# Generated by Django 4.2.4 on 2023-10-09 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mow_api", "0005_funfactcomment_main_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funfactcomment",
            name="main_comment",
        ),
    ]
