# Generated by Django 4.2.4 on 2023-10-22 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mow_api", "0007_remove_funfactcomment_downvote_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funfact",
            name="downvote",
        ),
        migrations.RemoveField(
            model_name="funfact",
            name="upvote",
        ),
    ]
